## Introduction to random matrices: practical session ##

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg

**Basic matrix and random variables manipulations in Python.** Don't hesitate to check the documentarion pages of numpy and scipy, for more information. 

Experimentation is strongly encouraged!

You can create matrices with the `array` command of numpy:

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix A:\n", A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


The transpose of a matrix is obtained via `np.transpose` or `.T`. Print the transpose of the above example.

In [3]:
# Solution


To extract the upper triangular part and the diagonal part of a matrix, you can use `np.triu` and `np.diag` respectively. 

Print the upper triangular and the diagonal part of $A$.

In [4]:
# Solution


Replace the diagonal part of $A$ by $[10,11,12]$ using `np.fill_diagonal`.

In [5]:
# Solution


Basic operations on matrices such as addition, soustraction and multiplication by a scalar are done by `+`, `-`, and `*` respectively, and multiplication of two matrices $A$ and $B$ is done by `np.dot(A,B)` or `A @ B`.

In [6]:
B = np.array([[-1, 0, 2], [3, 1, 4], [1, 0, -1]])
print("Matrix B:\n", B)

Matrix B:
 [[-1  0  2]
 [ 3  1  4]
 [ 1  0 -1]]


Print $A+B$, $A-B$, $2A$, $AB$ and $BA$.

In [7]:
# Solution


We can generate random samples using the `random` submodule of numpy, so for instance, the following command will provide a sample of 10 independant random variables with $\mathcal N(0,1)$ distribution. 

In [8]:
np.random.normal(0,1,10)

array([-1.40106009, -0.45532507,  1.66989388, -0.66961265,  0.09779903,
       -1.04724648,  0.44313069,  0.74926691, -0.79308834, -0.98645059])

Classical distribution such as the Binomial distribution or the uniform distribution are given by `np.random.binomial`, `np.random.uniform`.

We can also generate an array of i.i.d. random variables:

In [9]:
np.random.normal(0,1,(3,3))

array([[-0.67775112, -0.97894871, -0.04927008],
       [-0.98859687, -0.1089321 , -0.49349768],
       [-0.04384271,  0.72679017,  0.63764611]])

Generate a $5 \times  5$ matrix with i.i.d. symmetric Bernoulli random variables on $\{-1,1\}$.

In [10]:
# Solution


Eigenvalues and Eigenvectors of a matrix are obtained by the function `np.linalg.eig`. We can just use the function `np.linalg.eigvals`to compute the eigenvalues. Moreover, for Hermitian or symmetric matrices the function `np.linalg.eigh` performs better.

In [11]:
np.linalg.eig(A)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

Generate a $5\times 5$ symmetric random matrix with i.i.d. (up to the symmetry) coefficients distributed according your favorite distribution, and compare the eigenvalues computed by `np.linalg.eig` and `np.linalg.eigh`.

In [12]:
# Solution


### Wigner's Theorem and the semi-circular law ###

Illustrate the Wigner's theorem: 

Generate a $n \times n$ symmetric random matrix $X$ with i.i.d. real Gaussian coefficients (up to the symmetry) with mean zero and variance one.

In [13]:
# Solution


Define the density of the semi-circular distribution

In [14]:
# Solution


Plot the histogram of $\frac{1}{\sqrt n} X$ together with the density of the semi-circular distribution

In [15]:
# Solution


Do the same with a Hermitian random matrix with i.i.d. complex coefficients with mean zero and variance one.

In [16]:
# Solution


Illustrate the universality of Wigner's theorem by changing the distribution of the coefficients of $X$ (for instance uniform distribution on $[-1,1]$, Bernoulli distribution on $\{-1,1\}$, etc)

In [17]:
# Solution


Consider now the Student's t distribution. The Student's t distribution with parameter $c$ is the probability measure with density defined by:
$$
\frac{\Gamma(\frac{c+1}{2})}{\sqrt{\pi c} \Gamma(\frac{c}{2})} \left(1 + \frac{x^2}{c}   \right)^{-(c+1)/2}
$$
Plot the histogram of the empirical spectral distribution of $\frac{1}{\sqrt n} X$ with coefficient distributed according to the Student distribution with parameter 2 (use `np.random.standard_t`). What is happening here? 

In [18]:
# Solution


### A few hand computations! ###

To check your understanding of the proof of Wigner's Theorem by the method of moments, try the following exercise: give a proof of the Central Limit Theorem by the method of moments! (this is much easier than Wigner's Theorem) 

Let $(X_k)_{k\geq1}$ be a sequence of i.i.d. random variables, with bounded moments of any order, and such that $\mathbb E(X_1)=0$ and $\mathbb E(X_1^2)=1$. We recall that the double factorial at odd integers is defined by:
$$
(2k-1)!!=(2k-1)(2k-3)\cdots 3 \cdot1= \frac{(2k)!}{2^k k!}.
$$

1) Show that the moments of the Gaussian distribution are given by:
$$
\mathbb E \left( N^{2k}   \right) = (2k-1)!!, \quad \mathbb E \left( N^{2k+1}   \right)=0,
$$
where $N$ is distributed according to the $\mathcal N(0,1)$ distribution.

2) Show that the number of pairings of $\{1,\ldots,2k\}$ is $(2k-1)!!$, where a pairing of $\{1,\ldots,2k\}$ is a partition $\{V_1,\ldots,V_k\}$ such that $|V_i|=2$ for any $i\in \{1,\ldots,k\}$.

3) Expand
$$
\mathbb E \left[ \left( \frac{X_1+\cdots+X_n}{\sqrt n} \right)^k \right]
$$
and show that, as $n\to\infty$, the only terms in the expansion that gives a non-zero contribution are those for which each $X_i$ appears exactly twice.

4) Show that for all $k \geq 0$,
$$
\mathbb E \left[ \left( \frac{X_1+\cdots+X_n}{\sqrt n} \right)^k \right] \to \mathbb E \left( N^k  \right),
$$
as $n\to\infty$.

5) The Gaussian distribution has not a compact support, but is still characterized by its moments (see for instance, Billingsley, Probability and measure, chapter 30). Conclude. 

### Sample covariance matrices and the Marchenko-Pastur distribution ###

Now consider a $p\times n$ random matrix with i.i.d. $\mathcal N(0,1)$ coefficients. Plot the histogram of the eigenvalues of $\frac{1}{n} X X^\intercal$ together with the density of the Marchenko-Pastur distribution. Try different values of $p$ and $n$ (so $\frac{p}{n}$ is greater or less than 1). 

In [19]:
# Solution


### Concentration of Gaussian vectors.

Consider a Gaussian vector $X \in \mathbb R^p$ with covariance matrix the identity. Plot the histogram of $f(X)$, for the 1-norm $||\cdot||_1$, the $2$-norm $||\cdot||_2$ and the supremum norm $||\cdot||_\infty$, for 1000 realisations of $X$, for $p=1,10,100,1000$. You can use `np.linalg.norm(..., ord=k)` for the $k$-norm.

In [20]:
# Solution



### Fluctuations of the largest eigenvalue ###

For both Wigner matrices and sample covariance matrices, the largest eigenvalue converges to the edge of the bulk. One can show that the fluctuations are governed by the Tracy-Widom distribution. More precisely: 

Generate $N=500$ GOE matrices, and plot the histogram of the largest eigenvalue (note that it can be a bit long).

In [21]:
# Solution


In fact, the fluctuations of the largest eigenvalue of the GOE ensemble is governed by the so-called Tracy-Widom distribution: for all $t\in \mathbb R$,
$$
\lim_{n\to\infty}\mathbb P\left(n^{1/6}(\lambda_\max - 2 \sqrt n) \leq t   \right) = F_{1}(t),
$$
where $F_{1}$ is the cumulative distribution function of the Tracy-Widom distribution (for the GOE case). This distribution is quite complicated to define (it is related to Painlevé equation). The following code gives an approximation of the density of the Tracy-Widom distribution (thanks to Zhenyu Liao for providing the code). $F_1$ corresponds to the GOE ensemble, $F_2$ to the GUE ensemble, and $F_4$ to the GSE ensemble.

In [22]:
import scipy.special

def tracy_widom_appx(x, i):
#
# TW ~ Gamma[k,theta]-alpha
#
# [pdf,cdf]=tracywidom_appx(x,i) for i=1,2,4 gives TW1, TW2, TW4
#

    kappx = [46.44604884387787, 79.6594870666346, 0, 146.0206131050228]   #  K, THETA, ALPHA
    thetaappx = [0.18605402228279347, 0.10103655775856243, 0, 0.05954454047933292]
    alphaappx = [9.848007781128567, 9.819607173436484, 0, 11.00161520109004]

    cdftwappx = cdfgamma(x+alphaappx[i-1], thetaappx[i-1], kappx[i-1])

    pdftwappx = pdfgamma(x+alphaappx[i-1], thetaappx[i-1], kappx[i-1])

    return pdftwappx, cdftwappx

# Probability density function

def pdfgamma(x, ta, ka):
    pdf = []
    for x_ in x:
        if x_ > 0:
            pdf.append(1/(scipy.special.gamma(ka)*ta**ka) * x_**(ka - 1) * np.exp(-x_/ta))
        else:
            pdf.append(0)
    return pdf

# Cumulative density function

def cdfgamma(x, ta, ka):
    cdf = []
    for x_ in x:
        if x_ > 0:
            cdf.append(scipy.special.gammainc(ka,x_/ta))
        else:
            cdf.append(0)
    return cdf

Note that the normalization in $n^{1/6}$ can be heuristically understand as follows: by the Wigner's theorem, one has
$$
n \mu_n \left( [2-\varepsilon,2]  \right) \approx n \int_{2-\varepsilon}^2 \sqrt{4-x^2} dx \approx n \varepsilon^{2/3},
$$
so $\varepsilon \sim n^{-2/3}$.

Plot the histogram of the largest eigenvalue of the GOE ensemble and compare to the Tracy-Widom distribution $F_1$.

In [23]:
# Solution


Try the same with a Wishart matrix. Hint: first try to understand the renormalization as for Wigner's matrices and compare to the Tracy-Widom distribution. Try the write out a statement about the fluctuations of the largest eigenvalue.

In [24]:
# Solution 


### Deformed models ###

We now consider deformed models of finite rank deterministic matrices by a random matrix.

We start with the additive case: let 
$$
M_n = \frac{1}{\sqrt n} X_n + A_n,
$$
where $X_n$ is a Wigner matrix, with, for instance, $\mathcal N(0,1)$ distribution, and $A_n$ a finite rank diagonal deterministic matrix. Start with a rank-one matrix $A_n$, so $A_n= \theta e_1e_1^\intercal$, where $e_1$ is the first vector of the canonical basis of $\mathbb R^n$. 
Plot the histogram of the eigenvalues of $M_n$ and compare to the semi-circular distribution. Try different values of $\theta$. An outlier will arise if and only if $\theta>1$, the outlier being $\theta + \frac{1}{\theta}$ (which is striclty greater than $2$). 

In [25]:
# Solution



Do the same with a finite rank matrix with several spikes.

In [26]:
# Solution


Now, perform the case of sample covariance matrices. Consider the model
$$
M_n = \frac{1}{n} YY^\intercal,
$$
where $Y=\Sigma^{1/2} X$, with $X$ a $p\times n$ Gaussian random matrix, and $\Sigma$ a $p \times p$ deterministic diagonal matrix, with finite rank. Start with the simplest example, where $\Sigma_{1,1}=\theta$, and $\Sigma_{i,i}=1$, for all $i\geq2$. 

In [27]:
# Solution


#### Population covariance estimation

Define for example, a diagonal matrix $\Sigma$ with $3$ different eigenvalues, for example $1,3,7$, with equal proportion. Plot the histogram of empirical eigenvalue distribution.

In [28]:
# Solution


Recall that by Bai and Silverstein Theorem, the Stieltjes transforms $m$ and $\tilde m$ of the limiting spectral distribution of the model $\frac{1}{n} \Sigma^{1/2} X X^\intercal \Sigma^{1/2}$ and $\frac{1}{n} X^\intercal \Sigma X$  satisfy the fixed point equation on $\mathbb C \setminus \mathbb R$:
$$
m(z) = \frac{1}{c}\tilde m(z) + \frac{1-c}{c z},   \quad\tilde m(z)= \left(- z + c\int \frac{t}{1+t \tilde m(z)} \nu(dt)   \right)^{-1},
$$
where $\nu$ is the limiting spectral distribution of $\Sigma$.

We can plot an approximation of the density of $m$ using a standard fixed point algorithm (one can show that such an algorithm converges). One has $m(z)=\lim_{l\to\infty} m^{(l)}(z)$, where we start by say $\tilde m(z)=0$, and for all $l\geq1$,
$$
m^{(l)}(z) = \frac{1}{c}\tilde m^{(l)}(z) + \frac{1-c}{c z},   \quad\tilde m^{(l+1)}(z)= \left(- z + c\int \frac{t}{1+t \tilde m^(l)(z)} \nu(dt)   \right)^{-1}.
$$
One should be careful since $m(z)$ is not defined for $z\in \text{supp} (\mu)$. So one has to perform the algorithm for $z$ close to the real axis, that is $z=x+i\varepsilon$, with $\varepsilon \ll 1$, (say $10^{-5}$), but the convergence can be quite slow.

Plot an approximation of the density of the distribution characterized by $m$ for the above example of $\Sigma$.

In [29]:
# Solution


Compare with the histogram of the eigenvalues of $\frac{1}{n} \Sigma^{1/2} X X^\intercal \Sigma^{1/2}$

In [30]:
# Solution


####  Population eigenvalue estimation

In view of the plot, it may be appear that averaging the sample eigenvalues of each component of the empirical spectral distribution provide a consistent estimator. But it is not the case, and such an estimator is indeed biased.

Visualization of the local behavior of the Stieltjes transform around an eigvanlue.

Assume $p<n$. The Stieltjes transform of the sample covariance $n\times n$ matrix $\frac1n Y^\intercal Y$, with $Y= \Sigma^{1/2} X$ is
$$
\frac{1}{n} \sum_{k=1}^p \frac{1}{\lambda_k-z} - \frac{n-p}{n} \frac{1}{z} 
$$
where $\lambda_1 \leq \cdots \leq \lambda_p$ are the sorted eigenvalues of $\frac1n Y Y^{\intercal}$ (and there are $n-p$ eigenvalues of $\frac1n Y^\intercal Y$ equal to 0).

It can be proved that the zeroes of the Stieltjes transform of the sample covariance $n\times n$ matrix $\frac1n Y^\intercal Y$ are given by the eigenvalues of the following matrix:
$$
\Lambda - \frac{1}{n}\sqrt \lambda \sqrt \lambda^\intercal,
$$
where $\Lambda$ is the diagonal $p\times p$ matrix $\text{diag}(\lambda_1,\ldots,\lambda_p)$, and $\lambda$ the column vector $(\lambda_1,\ldots,\lambda_p)$ in $\mathbb R^p$.

Plot the Stieltjes transform of the sample covariance matrix $\frac1n  Y^\intercal Y$, with $Y= \Sigma^{1/2} X$ near one eigenvalue.

In [31]:
# Solution


Now, Mestre has proved that for $\Sigma$ with eigenvalues $0<l_1<\ldots<l_k$ with multiplicities $N_1,\ldots,N_k$ (so $\sum_{j=1}^k N_j = p$), the following gives a consistent estimator for $l_a$:
$$
\hat l_a = \frac{n}{N_a} \sum_{j=N_1+\cdots+N_{a-1}+1}^{N_1+\cdots+N_{a}} \left( \lambda_j - \rho_j  \right),
$$
where $\rho_1,\ldots,\rho_p$ are the zeroes of the Stieltjes transform of $\frac1n Y^\intercal Y$.

For the above example for a population of 3 eigenvalues, compare the performance of the naive estimator of $l_a$ obtained by averaging the sample eigenvalues of each component of the empirical spectral distribution, and the above improved estimator.

In [32]:
# Solution
